<?php

function accounting_menu() {
  $items = array();
  $items['admin/settings/accounting'] = array(
    'title' => 'Accounting Settings',
    'description' => 'Settings for the accounting module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'accounting_settings_form',
    ),
    'access arguments' => array(
      'administer accounting',
    ),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'settings.inc',
  );

  $items['accounting/manage_forms'] = array(
    'title' => 'Manage Cheque Proposals',
    'description' => 'Manage cheque proposal.',
    'page callback' => 'accounting_lm_list_forms',
    'access arguments' => array(
      'accounting manage forms'
    ),
    'file' => 'manage_lm.inc'
  );

  $items['accounting/manage_forms/lm'] = array(
    'title' => 'Manage Lab Migration Forms',
    'description' => 'Manage lab migration forms sent by post.',
    'page callback' => 'accounting_lm_list_forms',
    'access arguments' => array(
      'accounting manage forms',
    ),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'manage_lm.inc',
  );

  $items['accounting/manage_forms/lm/form'] = array(
    'title' => 'Manage Cheque for User', 
    'description' => 'Manage cheques to be dispatched to the user.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'accounting_manage_lm_form',
    ),
    'access arguments' => array(
      'accounting manage forms',
    ),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'manage_lm.inc',
  );

  $items['accounting/manage_forms/tbc'] = array(
    'title' => 'Manage Textbook Companion Forms',
    'description' => 'Manage textbook companion forms sent by post.',
    'page callback' => 'manage_forms_tbc',
    'access arguments' => array(
      'accounting manage forms'
    ),
    'type' => MENU_LOCAL_TASK,
    'file' => 'manage_cheque_tbc.inc'
  );

  $items['accounting/manage_forms/tbc/user'] = array(
    'title' => 'Application Forms',
    'description' => 'Details of Appliction form sent by post.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'manage_forms_tbc_user_form'
    ),
    'access arguments' => array(
      'accounting manage forms user'
    ),
    //'type' => MENU_LOCAL_TASK,
    'file' => 'manage_cheque_tbc.inc'
  );

  $items['accounting/manage_forms/tbc/paper_submission'] = array(
    'title' => 'Application Submission',
    'description' => 'Application Submission',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'paper_submission_form'
    ),
    'access arguments' => array(
      'accounting manage forms'
    ),
    'type' => MENU_CALLBACK,
    'file' => 'manage_cheque_tbc.inc'
  );

  $items['accounting/cheque_contact/status'] = array(
    'title' => 'Cheque Status',
    'description' => 'Cheque Status',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'cheque_status_form'
    ),
    'access' => 'user_is_logged_in',
    'access arguments' => array(
      'accounting manage forms'
    ),
    'file' => 'manage_cheque_tbc.inc'
  );

  $items['accounting/contact_details/user'] = array(
    'title' => 'Update Contact Details',
    'description' => 'contact details for cheque',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'contact_details_form'
    ),
    'access arguments' => array(
      'update contact details'
    ),
    'file' => 'manage_cheque_tbc.inc'
  );

  return $items;
}

function accounting_permission() {
  return array(
    'accounting manage forms' => array(
      'title' => t('accounting manage forms'),
      'restrict access' => TRUE,
    ),

    'administer accounting' => array(
      'title' => t('administer accounting'),
      'restrict access' => TRUE,
    ),

    'accounting manage forms user' => array(
      'title' => t('accounting manage forms user'),
      'restrict access' => TRUE,
    ),

    'update contact details' => array(
      'title' => t('update contact details'),
      'restrict access' => TRUE,
    ),
  );
}
