<?php

function accounting_menu() {
  $items = array();
  $items['admin/settings/accounting'] = array(
    'title' => 'Accounting Settings',
    'description' => 'Settings for the accounting module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'accounting_settings_form',
    ),
    'access arguments' => array(
      'administer accounting',
    ),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'settings.inc',
  );

  $items['accounting/manage_forms'] = array(
    'title' => 'Manage Cheque Proposals',
    'description' => 'Manage cheque proposal.',
    'page callback' => 'accounting_lm_list_forms',
    'access arguments' => array(
      'accounting manage forms'
    ),
    'file' => 'manage_lm.inc'
  );

  $items['accounting/manage_forms/lm'] = array(
    'title' => 'Manage Lab Migration Forms',
    'description' => 'Manage lab migration forms sent by post.',
    'page callback' => 'accounting_lm_list_forms',
    'access arguments' => array(
      'accounting manage forms',
    ),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'manage_lm.inc',
  );

  $items['accounting/manage_forms/lm/form'] = array(
    'title' => 'Manage Cheque for User', 
    'description' => 'Manage cheques to be dispatched to the user.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'accounting_manage_lm_form',
    ),
    'access arguments' => array(
      'accounting manage forms',
    ),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'manage_lm.inc',
  );

  $items['accounting/manage_forms/tbc'] = array(
    'title' => 'Manage Textbook Companion Forms',
    'description' => 'Manage textbook companion forms sent by post.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'accounting_manage_tbc_form'
    ),
    'access arguments' => array(
      'accounting manage forms'
    ),
    'type' => MENU_LOCAL_TASK,
    'file' => 'manage_tbc.inc'
  );

  return $items;
}

function accounting_permission() {
  return array(
    'accounting manage forms' => array(
      'title' => t('accounting manage forms'),
      'restrict access' => TRUE,
    ),

    'administer accounting' => array(
      'title' => t('administer accounting'), 
      'restrict access' => TRUE,
    ),
  );
}
